use std::fmt;
use std::str::FromStr;

// ---------------------------------------------------------------------------
// Language – ISO 639-1
// ---------------------------------------------------------------------------

#[derive(Clone, Debug, PartialEq)]
pub enum Language {
    Afar,
    Abkhazian,
    Avestan,
    Afrikaans,
    Akan,
    Amharic,
    Aragonese,
    Arabic,
    Assamese,
    Avaric,
    Aymara,
    Azerbaijani,
    Bashkir,
    Belarusian,
    Bulgarian,
    Bislama,
    Bambara,
    Bengali,
    Tibetan,
    Breton,
    Bosnian,
    Catalan,
    Chechen,
    Chamorro,
    Corsican,
    Cree,
    Czech,
    ChurchSlavic,
    Chuvash,
    Welsh,
    Danish,
    German,
    Divehi,
    Dzongkha,
    Ewe,
    ModernGreek,
    English,
    Esperanto,
    Spanish,
    Estonian,
    Basque,
    Persian,
    Fulah,
    Finnish,
    Fijian,
    Faroese,
    French,
    WesternFrisian,
    Irish,
    ScottishGaelic,
    Galician,
    Guarani,
    Gujarati,
    Manx,
    Hausa,
    Hebrew,
    Hindi,
    HiriMotu,
    Croatian,
    HaitianCreole,
    Hungarian,
    Armenian,
    Herero,
    Interlingua,
    Indonesian,
    Interlingue,
    Igbo,
    SichuanYi,
    Inupiaq,
    Ido,
    Icelandic,
    Italian,
    Inuktitut,
    Japanese,
    Javanese,
    Georgian,
    Kongo,
    Kikuyu,
    Kuanyama,
    Kazakh,
    Kalaallisut,
    CentralKhmer,
    Kannada,
    Korean,
    Kanuri,
    Kashmiri,
    Kurdish,
    Komi,
    Cornish,
    Kyrgyz,
    Latin,
    Luxembourgish,
    Ganda,
    Limburgish,
    Lingala,
    Lao,
    Lithuanian,
    LubaKatanga,
    Latvian,
    Malagasy,
    Marshallese,
    Maori,
    Macedonian,
    Malayalam,
    Mongolian,
    Marathi,
    Malay,
    Maltese,
    Burmese,
    Nauru,
    NorwegianBokmal,
    NorthNdebele,
    Nepali,
    Ndonga,
    Dutch,
    NorwegianNynorsk,
    Norwegian,
    SouthNdebele,
    Navajo,
    Chichewa,
    Occitan,
    Ojibwa,
    Oromo,
    Oriya,
    Ossetian,
    Punjabi,
    Pali,
    Polish,
    Pashto,
    Portuguese,
    Quechua,
    Romansh,
    Rundi,
    Romanian,
    Russian,
    Kinyarwanda,
    Sanskrit,
    Sardinian,
    Sindhi,
    NorthernSami,
    Sango,
    Sinhala,
    Slovak,
    Slovenian,
    Samoan,
    Shona,
    Somali,
    Albanian,
    Serbian,
    Swati,
    SothoSouthern,
    Sundanese,
    Swedish,
    Swahili,
    Tamil,
    Telugu,
    Tajik,
    Thai,
    Tigrinya,
    Turkmen,
    Tagalog,
    Tswana,
    Tonga,
    Turkish,
    Tsonga,
    Tatar,
    Twi,
    Tahitian,
    Uyghur,
    Ukrainian,
    Urdu,
    Uzbek,
    Venda,
    Vietnamese,
    Volapuk,
    Walloon,
    Wolof,
    Xhosa,
    Yiddish,
    Yoruba,
    Zhuang,
    Chinese,
    Zulu,
}

impl fmt::Display for Language {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let code = match self {
            Language::Afar => "aa",
            Language::Abkhazian => "ab",
            Language::Avestan => "ae",
            Language::Afrikaans => "af",
            Language::Akan => "ak",
            Language::Amharic => "am",
            Language::Aragonese => "an",
            Language::Arabic => "ar",
            Language::Assamese => "as",
            Language::Avaric => "av",
            Language::Aymara => "ay",
            Language::Azerbaijani => "az",
            Language::Bashkir => "ba",
            Language::Belarusian => "be",
            Language::Bulgarian => "bg",
            Language::Bislama => "bi",
            Language::Bambara => "bm",
            Language::Bengali => "bn",
            Language::Tibetan => "bo",
            Language::Breton => "br",
            Language::Bosnian => "bs",
            Language::Catalan => "ca",
            Language::Chechen => "ce",
            Language::Chamorro => "ch",
            Language::Corsican => "co",
            Language::Cree => "cr",
            Language::Czech => "cs",
            Language::ChurchSlavic => "cu",
            Language::Chuvash => "cv",
            Language::Welsh => "cy",
            Language::Danish => "da",
            Language::German => "de",
            Language::Divehi => "dv",
            Language::Dzongkha => "dz",
            Language::Ewe => "ee",
            Language::ModernGreek => "el",
            Language::English => "en",
            Language::Esperanto => "eo",
            Language::Spanish => "es",
            Language::Estonian => "et",
            Language::Basque => "eu",
            Language::Persian => "fa",
            Language::Fulah => "ff",
            Language::Finnish => "fi",
            Language::Fijian => "fj",
            Language::Faroese => "fo",
            Language::French => "fr",
            Language::WesternFrisian => "fy",
            Language::Irish => "ga",
            Language::ScottishGaelic => "gd",
            Language::Galician => "gl",
            Language::Guarani => "gn",
            Language::Gujarati => "gu",
            Language::Manx => "gv",
            Language::Hausa => "ha",
            Language::Hebrew => "he",
            Language::Hindi => "hi",
            Language::HiriMotu => "ho",
            Language::Croatian => "hr",
            Language::HaitianCreole => "ht",
            Language::Hungarian => "hu",
            Language::Armenian => "hy",
            Language::Herero => "hz",
            Language::Interlingua => "ia",
            Language::Indonesian => "id",
            Language::Interlingue => "ie",
            Language::Igbo => "ig",
            Language::SichuanYi => "ii",
            Language::Inupiaq => "ik",
            Language::Ido => "io",
            Language::Icelandic => "is",
            Language::Italian => "it",
            Language::Inuktitut => "iu",
            Language::Japanese => "ja",
            Language::Javanese => "jv",
            Language::Georgian => "ka",
            Language::Kongo => "kg",
            Language::Kikuyu => "ki",
            Language::Kuanyama => "kj",
            Language::Kazakh => "kk",
            Language::Kalaallisut => "kl",
            Language::CentralKhmer => "km",
            Language::Kannada => "kn",
            Language::Korean => "ko",
            Language::Kanuri => "kr",
            Language::Kashmiri => "ks",
            Language::Kurdish => "ku",
            Language::Komi => "kv",
            Language::Cornish => "kw",
            Language::Kyrgyz => "ky",
            Language::Latin => "la",
            Language::Luxembourgish => "lb",
            Language::Ganda => "lg",
            Language::Limburgish => "li",
            Language::Lingala => "ln",
            Language::Lao => "lo",
            Language::Lithuanian => "lt",
            Language::LubaKatanga => "lu",
            Language::Latvian => "lv",
            Language::Malagasy => "mg",
            Language::Marshallese => "mh",
            Language::Maori => "mi",
            Language::Macedonian => "mk",
            Language::Malayalam => "ml",
            Language::Mongolian => "mn",
            Language::Marathi => "mr",
            Language::Malay => "ms",
            Language::Maltese => "mt",
            Language::Burmese => "my",
            Language::Nauru => "na",
            Language::NorwegianBokmal => "nb",
            Language::NorthNdebele => "nd",
            Language::Nepali => "ne",
            Language::Ndonga => "ng",
            Language::Dutch => "nl",
            Language::NorwegianNynorsk => "nn",
            Language::Norwegian => "no",
            Language::SouthNdebele => "nr",
            Language::Navajo => "nv",
            Language::Chichewa => "ny",
            Language::Occitan => "oc",
            Language::Ojibwa => "oj",
            Language::Oromo => "om",
            Language::Oriya => "or",
            Language::Ossetian => "os",
            Language::Punjabi => "pa",
            Language::Pali => "pi",
            Language::Polish => "pl",
            Language::Pashto => "ps",
            Language::Portuguese => "pt",
            Language::Quechua => "qu",
            Language::Romansh => "rm",
            Language::Rundi => "rn",
            Language::Romanian => "ro",
            Language::Russian => "ru",
            Language::Kinyarwanda => "rw",
            Language::Sanskrit => "sa",
            Language::Sardinian => "sc",
            Language::Sindhi => "sd",
            Language::NorthernSami => "se",
            Language::Sango => "sg",
            Language::Sinhala => "si",
            Language::Slovak => "sk",
            Language::Slovenian => "sl",
            Language::Samoan => "sm",
            Language::Shona => "sn",
            Language::Somali => "so",
            Language::Albanian => "sq",
            Language::Serbian => "sr",
            Language::Swati => "ss",
            Language::SothoSouthern => "st",
            Language::Sundanese => "su",
            Language::Swedish => "sv",
            Language::Swahili => "sw",
            Language::Tamil => "ta",
            Language::Telugu => "te",
            Language::Tajik => "tg",
            Language::Thai => "th",
            Language::Tigrinya => "ti",
            Language::Turkmen => "tk",
            Language::Tagalog => "tl",
            Language::Tswana => "tn",
            Language::Tonga => "to",
            Language::Turkish => "tr",
            Language::Tsonga => "ts",
            Language::Tatar => "tt",
            Language::Twi => "tw",
            Language::Tahitian => "ty",
            Language::Uyghur => "ug",
            Language::Ukrainian => "uk",
            Language::Urdu => "ur",
            Language::Uzbek => "uz",
            Language::Venda => "ve",
            Language::Vietnamese => "vi",
            Language::Volapuk => "vo",
            Language::Walloon => "wa",
            Language::Wolof => "wo",
            Language::Xhosa => "xh",
            Language::Yiddish => "yi",
            Language::Yoruba => "yo",
            Language::Zhuang => "za",
            Language::Chinese => "zh",
            Language::Zulu => "zu",
        };
        f.write_str(code)
    }
}

impl FromStr for Language {
    type Err = ();

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "aa" => Ok(Language::Afar),
            "ab" => Ok(Language::Abkhazian),
            "ae" => Ok(Language::Avestan),
            "af" => Ok(Language::Afrikaans),
            "ak" => Ok(Language::Akan),
            "am" => Ok(Language::Amharic),
            "an" => Ok(Language::Aragonese),
            "ar" => Ok(Language::Arabic),
            "as" => Ok(Language::Assamese),
            "av" => Ok(Language::Avaric),
            "ay" => Ok(Language::Aymara),
            "az" => Ok(Language::Azerbaijani),
            "ba" => Ok(Language::Bashkir),
            "be" => Ok(Language::Belarusian),
            "bg" => Ok(Language::Bulgarian),
            "bi" => Ok(Language::Bislama),
            "bm" => Ok(Language::Bambara),
            "bn" => Ok(Language::Bengali),
            "bo" => Ok(Language::Tibetan),
            "br" => Ok(Language::Breton),
            "bs" => Ok(Language::Bosnian),
            "ca" => Ok(Language::Catalan),
            "ce" => Ok(Language::Chechen),
            "ch" => Ok(Language::Chamorro),
            "co" => Ok(Language::Corsican),
            "cr" => Ok(Language::Cree),
            "cs" => Ok(Language::Czech),
            "cu" => Ok(Language::ChurchSlavic),
            "cv" => Ok(Language::Chuvash),
            "cy" => Ok(Language::Welsh),
            "da" => Ok(Language::Danish),
            "de" => Ok(Language::German),
            "dv" => Ok(Language::Divehi),
            "dz" => Ok(Language::Dzongkha),
            "ee" => Ok(Language::Ewe),
            "el" => Ok(Language::ModernGreek),
            "en" => Ok(Language::English),
            "eo" => Ok(Language::Esperanto),
            "es" => Ok(Language::Spanish),
            "et" => Ok(Language::Estonian),
            "eu" => Ok(Language::Basque),
            "fa" => Ok(Language::Persian),
            "ff" => Ok(Language::Fulah),
            "fi" => Ok(Language::Finnish),
            "fj" => Ok(Language::Fijian),
            "fo" => Ok(Language::Faroese),
            "fr" => Ok(Language::French),
            "fy" => Ok(Language::WesternFrisian),
            "ga" => Ok(Language::Irish),
            "gd" => Ok(Language::ScottishGaelic),
            "gl" => Ok(Language::Galician),
            "gn" => Ok(Language::Guarani),
            "gu" => Ok(Language::Gujarati),
            "gv" => Ok(Language::Manx),
            "ha" => Ok(Language::Hausa),
            "he" => Ok(Language::Hebrew),
            "hi" => Ok(Language::Hindi),
            "ho" => Ok(Language::HiriMotu),
            "hr" => Ok(Language::Croatian),
            "ht" => Ok(Language::HaitianCreole),
            "hu" => Ok(Language::Hungarian),
            "hy" => Ok(Language::Armenian),
            "hz" => Ok(Language::Herero),
            "ia" => Ok(Language::Interlingua),
            "id" => Ok(Language::Indonesian),
            "ie" => Ok(Language::Interlingue),
            "ig" => Ok(Language::Igbo),
            "ii" => Ok(Language::SichuanYi),
            "ik" => Ok(Language::Inupiaq),
            "io" => Ok(Language::Ido),
            "is" => Ok(Language::Icelandic),
            "it" => Ok(Language::Italian),
            "iu" => Ok(Language::Inuktitut),
            "ja" => Ok(Language::Japanese),
            "jv" => Ok(Language::Javanese),
            "ka" => Ok(Language::Georgian),
            "kg" => Ok(Language::Kongo),
            "ki" => Ok(Language::Kikuyu),
            "kj" => Ok(Language::Kuanyama),
            "kk" => Ok(Language::Kazakh),
            "kl" => Ok(Language::Kalaallisut),
            "km" => Ok(Language::CentralKhmer),
            "kn" => Ok(Language::Kannada),
            "ko" => Ok(Language::Korean),
            "kr" => Ok(Language::Kanuri),
            "ks" => Ok(Language::Kashmiri),
            "ku" => Ok(Language::Kurdish),
            "kv" => Ok(Language::Komi),
            "kw" => Ok(Language::Cornish),
            "ky" => Ok(Language::Kyrgyz),
            "la" => Ok(Language::Latin),
            "lb" => Ok(Language::Luxembourgish),
            "lg" => Ok(Language::Ganda),
            "li" => Ok(Language::Limburgish),
            "ln" => Ok(Language::Lingala),
            "lo" => Ok(Language::Lao),
            "lt" => Ok(Language::Lithuanian),
            "lu" => Ok(Language::LubaKatanga),
            "lv" => Ok(Language::Latvian),
            "mg" => Ok(Language::Malagasy),
            "mh" => Ok(Language::Marshallese),
            "mi" => Ok(Language::Maori),
            "mk" => Ok(Language::Macedonian),
            "ml" => Ok(Language::Malayalam),
            "mn" => Ok(Language::Mongolian),
            "mr" => Ok(Language::Marathi),
            "ms" => Ok(Language::Malay),
            "mt" => Ok(Language::Maltese),
            "my" => Ok(Language::Burmese),
            "na" => Ok(Language::Nauru),
            "nb" => Ok(Language::NorwegianBokmal),
            "nd" => Ok(Language::NorthNdebele),
            "ne" => Ok(Language::Nepali),
            "ng" => Ok(Language::Ndonga),
            "nl" => Ok(Language::Dutch),
            "nn" => Ok(Language::NorwegianNynorsk),
            "no" => Ok(Language::Norwegian),
            "nr" => Ok(Language::SouthNdebele),
            "nv" => Ok(Language::Navajo),
            "ny" => Ok(Language::Chichewa),
            "oc" => Ok(Language::Occitan),
            "oj" => Ok(Language::Ojibwa),
            "om" => Ok(Language::Oromo),
            "or" => Ok(Language::Oriya),
            "os" => Ok(Language::Ossetian),
            "pa" => Ok(Language::Punjabi),
            "pi" => Ok(Language::Pali),
            "pl" => Ok(Language::Polish),
            "ps" => Ok(Language::Pashto),
            "pt" => Ok(Language::Portuguese),
            "qu" => Ok(Language::Quechua),
            "rm" => Ok(Language::Romansh),
            "rn" => Ok(Language::Rundi),
            "ro" => Ok(Language::Romanian),
            "ru" => Ok(Language::Russian),
            "rw" => Ok(Language::Kinyarwanda),
            "sa" => Ok(Language::Sanskrit),
            "sc" => Ok(Language::Sardinian),
            "sd" => Ok(Language::Sindhi),
            "se" => Ok(Language::NorthernSami),
            "sg" => Ok(Language::Sango),
            "si" => Ok(Language::Sinhala),
            "sk" => Ok(Language::Slovak),
            "sl" => Ok(Language::Slovenian),
            "sm" => Ok(Language::Samoan),
            "sn" => Ok(Language::Shona),
            "so" => Ok(Language::Somali),
            "sq" => Ok(Language::Albanian),
            "sr" => Ok(Language::Serbian),
            "ss" => Ok(Language::Swati),
            "st" => Ok(Language::SothoSouthern),
            "su" => Ok(Language::Sundanese),
            "sv" => Ok(Language::Swedish),
            "sw" => Ok(Language::Swahili),
            "ta" => Ok(Language::Tamil),
            "te" => Ok(Language::Telugu),
            "tg" => Ok(Language::Tajik),
            "th" => Ok(Language::Thai),
            "ti" => Ok(Language::Tigrinya),
            "tk" => Ok(Language::Turkmen),
            "tl" => Ok(Language::Tagalog),
            "tn" => Ok(Language::Tswana),
            "to" => Ok(Language::Tonga),
            "tr" => Ok(Language::Turkish),
            "ts" => Ok(Language::Tsonga),
            "tt" => Ok(Language::Tatar),
            "tw" => Ok(Language::Twi),
            "ty" => Ok(Language::Tahitian),
            "ug" => Ok(Language::Uyghur),
            "uk" => Ok(Language::Ukrainian),
            "ur" => Ok(Language::Urdu),
            "uz" => Ok(Language::Uzbek),
            "ve" => Ok(Language::Venda),
            "vi" => Ok(Language::Vietnamese),
            "vo" => Ok(Language::Volapuk),
            "wa" => Ok(Language::Walloon),
            "wo" => Ok(Language::Wolof),
            "xh" => Ok(Language::Xhosa),
            "yi" => Ok(Language::Yiddish),
            "yo" => Ok(Language::Yoruba),
            "za" => Ok(Language::Zhuang),
            "zh" => Ok(Language::Chinese),
            "zu" => Ok(Language::Zulu),
            _ => Err(()),
        }
    }
}

// ---------------------------------------------------------------------------
// Script – ISO 15924
// ---------------------------------------------------------------------------

#[derive(Clone, Debug, PartialEq)]
pub enum Script {
    Arab,
    Armn,
    Bali,
    Batk,
    Beng,
    Bopo,
    Brai,
    Bugi,
    Cprt,
    Cyrl,
    Deva,
    Ethi,
    Geor,
    Goth,
    Grek,
    Gujr,
    Guru,
    Hang,
    Hans,
    Hant,
    Hebr,
    Hira,
    Jpan,
    Kana,
    Khar,
    Khmr,
    Knda,
    Kore,
    Laoo,
    Latn,
    Limb,
    Linb,
    Mlym,
    Mong,
    Mymr,
    Ogam,
    Orya,
    Phag,
    Runr,
    Shaw,
    Sinh,
    Syrc,
    Taml,
    Talu,
    Telu,
    Tfng,
    Thaa,
    Thai,
    Tibt,
    Tglg,
    Ugar,
}

impl fmt::Display for Script {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let code = match self {
            Script::Arab => "Arab",
            Script::Armn => "Armn",
            Script::Bali => "Bali",
            Script::Batk => "Batk",
            Script::Beng => "Beng",
            Script::Bopo => "Bopo",
            Script::Brai => "Brai",
            Script::Bugi => "Bugi",
            Script::Cprt => "Cprt",
            Script::Cyrl => "Cyrl",
            Script::Deva => "Deva",
            Script::Ethi => "Ethi",
            Script::Geor => "Geor",
            Script::Goth => "Goth",
            Script::Grek => "Grek",
            Script::Gujr => "Gujr",
            Script::Guru => "Guru",
            Script::Hang => "Hang",
            Script::Hans => "Hans",
            Script::Hant => "Hant",
            Script::Hebr => "Hebr",
            Script::Hira => "Hira",
            Script::Jpan => "Jpan",
            Script::Kana => "Kana",
            Script::Khar => "Khar",
            Script::Khmr => "Khmr",
            Script::Knda => "Knda",
            Script::Kore => "Kore",
            Script::Laoo => "Laoo",
            Script::Latn => "Latn",
            Script::Limb => "Limb",
            Script::Linb => "Linb",
            Script::Mlym => "Mlym",
            Script::Mong => "Mong",
            Script::Mymr => "Mymr",
            Script::Ogam => "Ogam",
            Script::Orya => "Orya",
            Script::Phag => "Phag",
            Script::Runr => "Runr",
            Script::Shaw => "Shaw",
            Script::Sinh => "Sinh",
            Script::Syrc => "Syrc",
            Script::Taml => "Taml",
            Script::Talu => "Talu",
            Script::Telu => "Telu",
            Script::Tfng => "Tfng",
            Script::Thaa => "Thaa",
            Script::Thai => "Thai",
            Script::Tibt => "Tibt",
            Script::Tglg => "Tglg",
            Script::Ugar => "Ugar",
        };
        f.write_str(code)
    }
}

impl FromStr for Script {
    type Err = ();

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Arab" => Ok(Script::Arab),
            "Armn" => Ok(Script::Armn),
            "Bali" => Ok(Script::Bali),
            "Batk" => Ok(Script::Batk),
            "Beng" => Ok(Script::Beng),
            "Bopo" => Ok(Script::Bopo),
            "Brai" => Ok(Script::Brai),
            "Bugi" => Ok(Script::Bugi),
            "Cprt" => Ok(Script::Cprt),
            "Cyrl" => Ok(Script::Cyrl),
            "Deva" => Ok(Script::Deva),
            "Ethi" => Ok(Script::Ethi),
            "Geor" => Ok(Script::Geor),
            "Goth" => Ok(Script::Goth),
            "Grek" => Ok(Script::Grek),
            "Gujr" => Ok(Script::Gujr),
            "Guru" => Ok(Script::Guru),
            "Hang" => Ok(Script::Hang),
            "Hans" => Ok(Script::Hans),
            "Hant" => Ok(Script::Hant),
            "Hebr" => Ok(Script::Hebr),
            "Hira" => Ok(Script::Hira),
            "Jpan" => Ok(Script::Jpan),
            "Kana" => Ok(Script::Kana),
            "Khar" => Ok(Script::Khar),
            "Khmr" => Ok(Script::Khmr),
            "Knda" => Ok(Script::Knda),
            "Kore" => Ok(Script::Kore),
            "Laoo" => Ok(Script::Laoo),
            "Latn" => Ok(Script::Latn),
            "Limb" => Ok(Script::Limb),
            "Linb" => Ok(Script::Linb),
            "Mlym" => Ok(Script::Mlym),
            "Mong" => Ok(Script::Mong),
            "Mymr" => Ok(Script::Mymr),
            "Ogam" => Ok(Script::Ogam),
            "Orya" => Ok(Script::Orya),
            "Phag" => Ok(Script::Phag),
            "Runr" => Ok(Script::Runr),
            "Shaw" => Ok(Script::Shaw),
            "Sinh" => Ok(Script::Sinh),
            "Syrc" => Ok(Script::Syrc),
            "Taml" => Ok(Script::Taml),
            "Talu" => Ok(Script::Talu),
            "Telu" => Ok(Script::Telu),
            "Tfng" => Ok(Script::Tfng),
            "Thaa" => Ok(Script::Thaa),
            "Thai" => Ok(Script::Thai),
            "Tibt" => Ok(Script::Tibt),
            "Tglg" => Ok(Script::Tglg),
            "Ugar" => Ok(Script::Ugar),
            _ => Err(()),
        }
    }
}

// ---------------------------------------------------------------------------
// Region – ISO 3166-1 alpha-2
// ---------------------------------------------------------------------------

#[derive(Clone, Debug, PartialEq)]
pub enum Region {
    Ad,
    Ae,
    Af,
    Ag,
    Ai,
    Al,
    Am,
    Ao,
    Aq,
    Ar,
    As,
    At,
    Au,
    Aw,
    Ax,
    Az,
    Ba,
    Bb,
    Bd,
    Be,
    Bf,
    Bg,
    Bh,
    Bi,
    Bj,
    Bl,
    Bm,
    Bn,
    Bo,
    Bq,
    Br,
    Bs,
    Bt,
    Bv,
    Bw,
    By,
    Bz,
    Ca,
    Cc,
    Cd,
    Cf,
    Cg,
    Ch,
    Ci,
    Ck,
    Cl,
    Cm,
    Cn,
    Co,
    Cr,
    Cu,
    Cv,
    Cw,
    Cx,
    Cy,
    Cz,
    De,
    Dj,
    Dk,
    Dm,
    Do,
    Dz,
    Ec,
    Ee,
    Eg,
    Eh,
    Er,
    Es,
    Et,
    Fi,
    Fj,
    Fk,
    Fm,
    Fo,
    Fr,
    Ga,
    Gb,
    Gd,
    Ge,
    Gf,
    Gg,
    Gh,
    Gi,
    Gl,
    Gm,
    Gn,
    Gp,
    Gq,
    Gr,
    Gs,
    Gt,
    Gu,
    Gw,
    Gy,
    Hk,
    Hm,
    Hn,
    Hr,
    Ht,
    Hu,
    Id,
    Ie,
    Il,
    Im,
    In,
    Io,
    Iq,
    Ir,
    Is,
    It,
    Je,
    Jm,
    Jo,
    Jp,
    Ke,
    Kg,
    Kh,
    Ki,
    Km,
    Kn,
    Kp,
    Kr,
    Kw,
    Ky,
    Kz,
    La,
    Lb,
    Lc,
    Li,
    Lk,
    Lr,
    Ls,
    Lt,
    Lu,
    Lv,
    Ly,
    Ma,
    Mc,
    Md,
    Me,
    Mf,
    Mg,
    Mh,
    Mk,
    Ml,
    Mm,
    Mn,
    Mo,
    Mp,
    Mq,
    Mr,
    Ms,
    Mt,
    Mu,
    Mv,
    Mw,
    Mx,
    My,
    Mz,
    Na,
    Nc,
    Ne,
    Nf,
    Ng,
    Ni,
    Nl,
    No,
    Np,
    Nr,
    Nu,
    Nz,
    Om,
    Pa,
    Pe,
    Pf,
    Pg,
    Ph,
    Pk,
    Pl,
    Pm,
    Pn,
    Pr,
    Ps,
    Pt,
    Pw,
    Py,
    Qa,
    Re,
    Ro,
    Rs,
    Ru,
    Rw,
    Sa,
    Sb,
    Sc,
    Sd,
    Se,
    Sg,
    Sh,
    Si,
    Sj,
    Sk,
    Sl,
    Sm,
    Sn,
    So,
    Sr,
    Ss,
    St,
    Sv,
    Sx,
    Sy,
    Sz,
    Tc,
    Td,
    Tf,
    Tg,
    Th,
    Tj,
    Tk,
    Tl,
    Tm,
    Tn,
    To,
    Tr,
    Tt,
    Tv,
    Tw,
    Tz,
    Ua,
    Ug,
    Um,
    Us,
    Uy,
    Uz,
    Va,
    Vc,
    Ve,
    Vg,
    Vi,
    Vn,
    Vu,
    Wf,
    Ws,
    Ye,
    Yt,
    Za,
    Zm,
    Zw,
}

impl fmt::Display for Region {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let code = match self {
            Region::Ad => "AD",
            Region::Ae => "AE",
            Region::Af => "AF",
            Region::Ag => "AG",
            Region::Ai => "AI",
            Region::Al => "AL",
            Region::Am => "AM",
            Region::Ao => "AO",
            Region::Aq => "AQ",
            Region::Ar => "AR",
            Region::As => "AS",
            Region::At => "AT",
            Region::Au => "AU",
            Region::Aw => "AW",
            Region::Ax => "AX",
            Region::Az => "AZ",
            Region::Ba => "BA",
            Region::Bb => "BB",
            Region::Bd => "BD",
            Region::Be => "BE",
            Region::Bf => "BF",
            Region::Bg => "BG",
            Region::Bh => "BH",
            Region::Bi => "BI",
            Region::Bj => "BJ",
            Region::Bl => "BL",
            Region::Bm => "BM",
            Region::Bn => "BN",
            Region::Bo => "BO",
            Region::Bq => "BQ",
            Region::Br => "BR",
            Region::Bs => "BS",
            Region::Bt => "BT",
            Region::Bv => "BV",
            Region::Bw => "BW",
            Region::By => "BY",
            Region::Bz => "BZ",
            Region::Ca => "CA",
            Region::Cc => "CC",
            Region::Cd => "CD",
            Region::Cf => "CF",
            Region::Cg => "CG",
            Region::Ch => "CH",
            Region::Ci => "CI",
            Region::Ck => "CK",
            Region::Cl => "CL",
            Region::Cm => "CM",
            Region::Cn => "CN",
            Region::Co => "CO",
            Region::Cr => "CR",
            Region::Cu => "CU",
            Region::Cv => "CV",
            Region::Cw => "CW",
            Region::Cx => "CX",
            Region::Cy => "CY",
            Region::Cz => "CZ",
            Region::De => "DE",
            Region::Dj => "DJ",
            Region::Dk => "DK",
            Region::Dm => "DM",
            Region::Do => "DO",
            Region::Dz => "DZ",
            Region::Ec => "EC",
            Region::Ee => "EE",
            Region::Eg => "EG",
            Region::Eh => "EH",
            Region::Er => "ER",
            Region::Es => "ES",
            Region::Et => "ET",
            Region::Fi => "FI",
            Region::Fj => "FJ",
            Region::Fk => "FK",
            Region::Fm => "FM",
            Region::Fo => "FO",
            Region::Fr => "FR",
            Region::Ga => "GA",
            Region::Gb => "GB",
            Region::Gd => "GD",
            Region::Ge => "GE",
            Region::Gf => "GF",
            Region::Gg => "GG",
            Region::Gh => "GH",
            Region::Gi => "GI",
            Region::Gl => "GL",
            Region::Gm => "GM",
            Region::Gn => "GN",
            Region::Gp => "GP",
            Region::Gq => "GQ",
            Region::Gr => "GR",
            Region::Gs => "GS",
            Region::Gt => "GT",
            Region::Gu => "GU",
            Region::Gw => "GW",
            Region::Gy => "GY",
            Region::Hk => "HK",
            Region::Hm => "HM",
            Region::Hn => "HN",
            Region::Hr => "HR",
            Region::Ht => "HT",
            Region::Hu => "HU",
            Region::Id => "ID",
            Region::Ie => "IE",
            Region::Il => "IL",
            Region::Im => "IM",
            Region::In => "IN",
            Region::Io => "IO",
            Region::Iq => "IQ",
            Region::Ir => "IR",
            Region::Is => "IS",
            Region::It => "IT",
            Region::Je => "JE",
            Region::Jm => "JM",
            Region::Jo => "JO",
            Region::Jp => "JP",
            Region::Ke => "KE",
            Region::Kg => "KG",
            Region::Kh => "KH",
            Region::Ki => "KI",
            Region::Km => "KM",
            Region::Kn => "KN",
            Region::Kp => "KP",
            Region::Kr => "KR",
            Region::Kw => "KW",
            Region::Ky => "KY",
            Region::Kz => "KZ",
            Region::La => "LA",
            Region::Lb => "LB",
            Region::Lc => "LC",
            Region::Li => "LI",
            Region::Lk => "LK",
            Region::Lr => "LR",
            Region::Ls => "LS",
            Region::Lt => "LT",
            Region::Lu => "LU",
            Region::Lv => "LV",
            Region::Ly => "LY",
            Region::Ma => "MA",
            Region::Mc => "MC",
            Region::Md => "MD",
            Region::Me => "ME",
            Region::Mf => "MF",
            Region::Mg => "MG",
            Region::Mh => "MH",
            Region::Mk => "MK",
            Region::Ml => "ML",
            Region::Mm => "MM",
            Region::Mn => "MN",
            Region::Mo => "MO",
            Region::Mp => "MP",
            Region::Mq => "MQ",
            Region::Mr => "MR",
            Region::Ms => "MS",
            Region::Mt => "MT",
            Region::Mu => "MU",
            Region::Mv => "MV",
            Region::Mw => "MW",
            Region::Mx => "MX",
            Region::My => "MY",
            Region::Mz => "MZ",
            Region::Na => "NA",
            Region::Nc => "NC",
            Region::Ne => "NE",
            Region::Nf => "NF",
            Region::Ng => "NG",
            Region::Ni => "NI",
            Region::Nl => "NL",
            Region::No => "NO",
            Region::Np => "NP",
            Region::Nr => "NR",
            Region::Nu => "NU",
            Region::Nz => "NZ",
            Region::Om => "OM",
            Region::Pa => "PA",
            Region::Pe => "PE",
            Region::Pf => "PF",
            Region::Pg => "PG",
            Region::Ph => "PH",
            Region::Pk => "PK",
            Region::Pl => "PL",
            Region::Pm => "PM",
            Region::Pn => "PN",
            Region::Pr => "PR",
            Region::Ps => "PS",
            Region::Pt => "PT",
            Region::Pw => "PW",
            Region::Py => "PY",
            Region::Qa => "QA",
            Region::Re => "RE",
            Region::Ro => "RO",
            Region::Rs => "RS",
            Region::Ru => "RU",
            Region::Rw => "RW",
            Region::Sa => "SA",
            Region::Sb => "SB",
            Region::Sc => "SC",
            Region::Sd => "SD",
            Region::Se => "SE",
            Region::Sg => "SG",
            Region::Sh => "SH",
            Region::Si => "SI",
            Region::Sj => "SJ",
            Region::Sk => "SK",
            Region::Sl => "SL",
            Region::Sm => "SM",
            Region::Sn => "SN",
            Region::So => "SO",
            Region::Sr => "SR",
            Region::Ss => "SS",
            Region::St => "ST",
            Region::Sv => "SV",
            Region::Sx => "SX",
            Region::Sy => "SY",
            Region::Sz => "SZ",
            Region::Tc => "TC",
            Region::Td => "TD",
            Region::Tf => "TF",
            Region::Tg => "TG",
            Region::Th => "TH",
            Region::Tj => "TJ",
            Region::Tk => "TK",
            Region::Tl => "TL",
            Region::Tm => "TM",
            Region::Tn => "TN",
            Region::To => "TO",
            Region::Tr => "TR",
            Region::Tt => "TT",
            Region::Tv => "TV",
            Region::Tw => "TW",
            Region::Tz => "TZ",
            Region::Ua => "UA",
            Region::Ug => "UG",
            Region::Um => "UM",
            Region::Us => "US",
            Region::Uy => "UY",
            Region::Uz => "UZ",
            Region::Va => "VA",
            Region::Vc => "VC",
            Region::Ve => "VE",
            Region::Vg => "VG",
            Region::Vi => "VI",
            Region::Vn => "VN",
            Region::Vu => "VU",
            Region::Wf => "WF",
            Region::Ws => "WS",
            Region::Ye => "YE",
            Region::Yt => "YT",
            Region::Za => "ZA",
            Region::Zm => "ZM",
            Region::Zw => "ZW",
        };
        f.write_str(code)
    }
}

impl FromStr for Region {
    type Err = ();

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_ascii_uppercase().as_str() {
            "AD" => Ok(Region::Ad),
            "AE" => Ok(Region::Ae),
            "AF" => Ok(Region::Af),
            "AG" => Ok(Region::Ag),
            "AI" => Ok(Region::Ai),
            "AL" => Ok(Region::Al),
            "AM" => Ok(Region::Am),
            "AO" => Ok(Region::Ao),
            "AQ" => Ok(Region::Aq),
            "AR" => Ok(Region::Ar),
            "AS" => Ok(Region::As),
            "AT" => Ok(Region::At),
            "AU" => Ok(Region::Au),
            "AW" => Ok(Region::Aw),
            "AX" => Ok(Region::Ax),
            "AZ" => Ok(Region::Az),
            "BA" => Ok(Region::Ba),
            "BB" => Ok(Region::Bb),
            "BD" => Ok(Region::Bd),
            "BE" => Ok(Region::Be),
            "BF" => Ok(Region::Bf),
            "BG" => Ok(Region::Bg),
            "BH" => Ok(Region::Bh),
            "BI" => Ok(Region::Bi),
            "BJ" => Ok(Region::Bj),
            "BL" => Ok(Region::Bl),
            "BM" => Ok(Region::Bm),
            "BN" => Ok(Region::Bn),
            "BO" => Ok(Region::Bo),
            "BQ" => Ok(Region::Bq),
            "BR" => Ok(Region::Br),
            "BS" => Ok(Region::Bs),
            "BT" => Ok(Region::Bt),
            "BV" => Ok(Region::Bv),
            "BW" => Ok(Region::Bw),
            "BY" => Ok(Region::By),
            "BZ" => Ok(Region::Bz),
            "CA" => Ok(Region::Ca),
            "CC" => Ok(Region::Cc),
            "CD" => Ok(Region::Cd),
            "CF" => Ok(Region::Cf),
            "CG" => Ok(Region::Cg),
            "CH" => Ok(Region::Ch),
            "CI" => Ok(Region::Ci),
            "CK" => Ok(Region::Ck),
            "CL" => Ok(Region::Cl),
            "CM" => Ok(Region::Cm),
            "CN" => Ok(Region::Cn),
            "CO" => Ok(Region::Co),
            "CR" => Ok(Region::Cr),
            "CU" => Ok(Region::Cu),
            "CV" => Ok(Region::Cv),
            "CW" => Ok(Region::Cw),
            "CX" => Ok(Region::Cx),
            "CY" => Ok(Region::Cy),
            "CZ" => Ok(Region::Cz),
            "DE" => Ok(Region::De),
            "DJ" => Ok(Region::Dj),
            "DK" => Ok(Region::Dk),
            "DM" => Ok(Region::Dm),
            "DO" => Ok(Region::Do),
            "DZ" => Ok(Region::Dz),
            "EC" => Ok(Region::Ec),
            "EE" => Ok(Region::Ee),
            "EG" => Ok(Region::Eg),
            "EH" => Ok(Region::Eh),
            "ER" => Ok(Region::Er),
            "ES" => Ok(Region::Es),
            "ET" => Ok(Region::Et),
            "FI" => Ok(Region::Fi),
            "FJ" => Ok(Region::Fj),
            "FK" => Ok(Region::Fk),
            "FM" => Ok(Region::Fm),
            "FO" => Ok(Region::Fo),
            "FR" => Ok(Region::Fr),
            "GA" => Ok(Region::Ga),
            "GB" => Ok(Region::Gb),
            "GD" => Ok(Region::Gd),
            "GE" => Ok(Region::Ge),
            "GF" => Ok(Region::Gf),
            "GG" => Ok(Region::Gg),
            "GH" => Ok(Region::Gh),
            "GI" => Ok(Region::Gi),
            "GL" => Ok(Region::Gl),
            "GM" => Ok(Region::Gm),
            "GN" => Ok(Region::Gn),
            "GP" => Ok(Region::Gp),
            "GQ" => Ok(Region::Gq),
            "GR" => Ok(Region::Gr),
            "GS" => Ok(Region::Gs),
            "GT" => Ok(Region::Gt),
            "GU" => Ok(Region::Gu),
            "GW" => Ok(Region::Gw),
            "GY" => Ok(Region::Gy),
            "HK" => Ok(Region::Hk),
            "HM" => Ok(Region::Hm),
            "HN" => Ok(Region::Hn),
            "HR" => Ok(Region::Hr),
            "HT" => Ok(Region::Ht),
            "HU" => Ok(Region::Hu),
            "ID" => Ok(Region::Id),
            "IE" => Ok(Region::Ie),
            "IL" => Ok(Region::Il),
            "IM" => Ok(Region::Im),
            "IN" => Ok(Region::In),
            "IO" => Ok(Region::Io),
            "IQ" => Ok(Region::Iq),
            "IR" => Ok(Region::Ir),
            "IS" => Ok(Region::Is),
            "IT" => Ok(Region::It),
            "JE" => Ok(Region::Je),
            "JM" => Ok(Region::Jm),
            "JO" => Ok(Region::Jo),
            "JP" => Ok(Region::Jp),
            "KE" => Ok(Region::Ke),
            "KG" => Ok(Region::Kg),
            "KH" => Ok(Region::Kh),
            "KI" => Ok(Region::Ki),
            "KM" => Ok(Region::Km),
            "KN" => Ok(Region::Kn),
            "KP" => Ok(Region::Kp),
            "KR" => Ok(Region::Kr),
            "KW" => Ok(Region::Kw),
            "KY" => Ok(Region::Ky),
            "KZ" => Ok(Region::Kz),
            "LA" => Ok(Region::La),
            "LB" => Ok(Region::Lb),
            "LC" => Ok(Region::Lc),
            "LI" => Ok(Region::Li),
            "LK" => Ok(Region::Lk),
            "LR" => Ok(Region::Lr),
            "LS" => Ok(Region::Ls),
            "LT" => Ok(Region::Lt),
            "LU" => Ok(Region::Lu),
            "LV" => Ok(Region::Lv),
            "LY" => Ok(Region::Ly),
            "MA" => Ok(Region::Ma),
            "MC" => Ok(Region::Mc),
            "MD" => Ok(Region::Md),
            "ME" => Ok(Region::Me),
            "MF" => Ok(Region::Mf),
            "MG" => Ok(Region::Mg),
            "MH" => Ok(Region::Mh),
            "MK" => Ok(Region::Mk),
            "ML" => Ok(Region::Ml),
            "MM" => Ok(Region::Mm),
            "MN" => Ok(Region::Mn),
            "MO" => Ok(Region::Mo),
            "MP" => Ok(Region::Mp),
            "MQ" => Ok(Region::Mq),
            "MR" => Ok(Region::Mr),
            "MS" => Ok(Region::Ms),
            "MT" => Ok(Region::Mt),
            "MU" => Ok(Region::Mu),
            "MV" => Ok(Region::Mv),
            "MW" => Ok(Region::Mw),
            "MX" => Ok(Region::Mx),
            "MY" => Ok(Region::My),
            "MZ" => Ok(Region::Mz),
            "NA" => Ok(Region::Na),
            "NC" => Ok(Region::Nc),
            "NE" => Ok(Region::Ne),
            "NF" => Ok(Region::Nf),
            "NG" => Ok(Region::Ng),
            "NI" => Ok(Region::Ni),
            "NL" => Ok(Region::Nl),
            "NO" => Ok(Region::No),
            "NP" => Ok(Region::Np),
            "NR" => Ok(Region::Nr),
            "NU" => Ok(Region::Nu),
            "NZ" => Ok(Region::Nz),
            "OM" => Ok(Region::Om),
            "PA" => Ok(Region::Pa),
            "PE" => Ok(Region::Pe),
            "PF" => Ok(Region::Pf),
            "PG" => Ok(Region::Pg),
            "PH" => Ok(Region::Ph),
            "PK" => Ok(Region::Pk),
            "PL" => Ok(Region::Pl),
            "PM" => Ok(Region::Pm),
            "PN" => Ok(Region::Pn),
            "PR" => Ok(Region::Pr),
            "PS" => Ok(Region::Ps),
            "PT" => Ok(Region::Pt),
            "PW" => Ok(Region::Pw),
            "PY" => Ok(Region::Py),
            "QA" => Ok(Region::Qa),
            "RE" => Ok(Region::Re),
            "RO" => Ok(Region::Ro),
            "RS" => Ok(Region::Rs),
            "RU" => Ok(Region::Ru),
            "RW" => Ok(Region::Rw),
            "SA" => Ok(Region::Sa),
            "SB" => Ok(Region::Sb),
            "SC" => Ok(Region::Sc),
            "SD" => Ok(Region::Sd),
            "SE" => Ok(Region::Se),
            "SG" => Ok(Region::Sg),
            "SH" => Ok(Region::Sh),
            "SI" => Ok(Region::Si),
            "SJ" => Ok(Region::Sj),
            "SK" => Ok(Region::Sk),
            "SL" => Ok(Region::Sl),
            "SM" => Ok(Region::Sm),
            "SN" => Ok(Region::Sn),
            "SO" => Ok(Region::So),
            "SR" => Ok(Region::Sr),
            "SS" => Ok(Region::Ss),
            "ST" => Ok(Region::St),
            "SV" => Ok(Region::Sv),
            "SX" => Ok(Region::Sx),
            "SY" => Ok(Region::Sy),
            "SZ" => Ok(Region::Sz),
            "TC" => Ok(Region::Tc),
            "TD" => Ok(Region::Td),
            "TF" => Ok(Region::Tf),
            "TG" => Ok(Region::Tg),
            "TH" => Ok(Region::Th),
            "TJ" => Ok(Region::Tj),
            "TK" => Ok(Region::Tk),
            "TL" => Ok(Region::Tl),
            "TM" => Ok(Region::Tm),
            "TN" => Ok(Region::Tn),
            "TO" => Ok(Region::To),
            "TR" => Ok(Region::Tr),
            "TT" => Ok(Region::Tt),
            "TV" => Ok(Region::Tv),
            "TW" => Ok(Region::Tw),
            "TZ" => Ok(Region::Tz),
            "UA" => Ok(Region::Ua),
            "UG" => Ok(Region::Ug),
            "UM" => Ok(Region::Um),
            "US" => Ok(Region::Us),
            "UY" => Ok(Region::Uy),
            "UZ" => Ok(Region::Uz),
            "VA" => Ok(Region::Va),
            "VC" => Ok(Region::Vc),
            "VE" => Ok(Region::Ve),
            "VG" => Ok(Region::Vg),
            "VI" => Ok(Region::Vi),
            "VN" => Ok(Region::Vn),
            "VU" => Ok(Region::Vu),
            "WF" => Ok(Region::Wf),
            "WS" => Ok(Region::Ws),
            "YE" => Ok(Region::Ye),
            "YT" => Ok(Region::Yt),
            "ZA" => Ok(Region::Za),
            "ZM" => Ok(Region::Zm),
            "ZW" => Ok(Region::Zw),
            _ => Err(()),
        }
    }
}

// ---------------------------------------------------------------------------
// LanguageTag – BCP 47 subset
// ---------------------------------------------------------------------------

#[derive(Clone, Debug, PartialEq)]
pub struct LanguageTag {
    pub language: Language,
    pub script: Option<Script>,
    pub region: Option<Region>,
}

impl fmt::Display for LanguageTag {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.language)?;
        if let Some(script) = &self.script {
            write!(f, "-{}", script)?;
        }
        if let Some(region) = &self.region {
            write!(f, "-{}", region)?;
        }
        Ok(())
    }
}

impl FromStr for LanguageTag {
    type Err = ();

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let mut parts = s.splitn(4, '-');

        let lang_str = parts.next().ok_or(())?;
        let language = Language::from_str(lang_str)?;

        let mut script: Option<Script> = None;
        let mut region: Option<Region> = None;

        if let Some(second) = parts.next() {
            if second.len() == 4 {
                script = Some(Script::from_str(second)?);
                // third part, if present, is the region
                if let Some(third) = parts.next() {
                    if third.len() == 2 {
                        region = Some(Region::from_str(third)?);
                    } else {
                        return Err(());
                    }
                }
            } else if second.len() == 2 {
                region = Some(Region::from_str(second)?);
            } else {
                return Err(());
            }
        }

        Ok(LanguageTag {
            language,
            script,
            region,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn language_display() {
        assert_eq!(Language::English.to_string(), "en");
        assert_eq!(Language::French.to_string(), "fr");
        assert_eq!(Language::Arabic.to_string(), "ar");
        assert_eq!(Language::Chinese.to_string(), "zh");
        assert_eq!(Language::Spanish.to_string(), "es");
    }

    #[test]
    fn language_from_str() {
        assert_eq!("en".parse::<Language>(), Ok(Language::English));
        assert_eq!("zh".parse::<Language>(), Ok(Language::Chinese));
        assert_eq!("xx".parse::<Language>(), Err(()));
    }

    #[test]
    fn script_display() {
        assert_eq!(Script::Latn.to_string(), "Latn");
        assert_eq!(Script::Hans.to_string(), "Hans");
        assert_eq!(Script::Arab.to_string(), "Arab");
    }

    #[test]
    fn script_from_str() {
        assert_eq!("Latn".parse::<Script>(), Ok(Script::Latn));
        assert_eq!("Cyrl".parse::<Script>(), Ok(Script::Cyrl));
        assert_eq!("Xxxx".parse::<Script>(), Err(()));
    }

    #[test]
    fn region_display() {
        assert_eq!(Region::Us.to_string(), "US");
        assert_eq!(Region::Gb.to_string(), "GB");
        assert_eq!(Region::Cn.to_string(), "CN");
    }

    #[test]
    fn region_from_str_case_insensitive() {
        assert_eq!("us".parse::<Region>(), Ok(Region::Us));
        assert_eq!("US".parse::<Region>(), Ok(Region::Us));
        assert_eq!("Us".parse::<Region>(), Ok(Region::Us));
        assert_eq!("XX".parse::<Region>(), Err(()));
    }

    #[test]
    fn language_tag_display() {
        let tag = LanguageTag {
            language: Language::English,
            script: None,
            region: None,
        };
        assert_eq!(tag.to_string(), "en");

        let tag = LanguageTag {
            language: Language::Chinese,
            script: Some(Script::Hans),
            region: None,
        };
        assert_eq!(tag.to_string(), "zh-Hans");

        let tag = LanguageTag {
            language: Language::Chinese,
            script: Some(Script::Hans),
            region: Some(Region::Cn),
        };
        assert_eq!(tag.to_string(), "zh-Hans-CN");
    }

    #[test]
    fn language_tag_from_str() {
        assert_eq!(
            "en".parse::<LanguageTag>(),
            Ok(LanguageTag {
                language: Language::English,
                script: None,
                region: None
            })
        );
        assert_eq!(
            "zh-Hans".parse::<LanguageTag>(),
            Ok(LanguageTag {
                language: Language::Chinese,
                script: Some(Script::Hans),
                region: None
            })
        );
        assert_eq!(
            "zh-Hans-CN".parse::<LanguageTag>(),
            Ok(LanguageTag {
                language: Language::Chinese,
                script: Some(Script::Hans),
                region: Some(Region::Cn),
            })
        );
        assert_eq!(
            "en-US".parse::<LanguageTag>(),
            Ok(LanguageTag {
                language: Language::English,
                script: None,
                region: Some(Region::Us)
            })
        );
    }
}
